# OUTPUT: travisci_out_kdoc

# 指定语言环境
language: python
# 指定需要sudo权限
sudo: required
# 指定python版本
python: 
  - 3.7.4
# 指定缓存模块，可选。缓存可加快编译速度。
#cache:
#  directories:
#    - node_modules

# 指定doc启动分支
branches:
  only:
    - dev 

before_install:
# texlive & texlive-xetex & texlive-xetex-extra（转换为pdf）
# 使用xelatex这个引擎为Pandoc提供pdf转换中文支持，Ubuntu12.04.5LTS需要 texlive-xetex texlive-latex-extra 这两个包，安装这两个包需要添加 texlive-backports/ppa 这个库。
#  - sudo apt-get install python-software-properties #这个在Travis下是不需要的
  - sudo add-apt-repository ppa:texlive-backports/ppa
  - sudo apt-get update
  - sudo apt-get install texlive-xetex texlive-latex-extra

# Start: Build Lifecycle
install:
# pandoc （提供基本转换环境）
# 针对Ubuntu12.04,5下安装pandoc如果使用cabal处理依赖关系总是出现版本不符合的问题，不知道如何解决，反而直接下载 deb包 来安装却非常简单，适合travis-ci虚拟机环境
  - wget https://github.com/jgm/pandoc/releases/download/1.17.1/pandoc-1.17.1-2-amd64.deb
  - sudo dpkg -i pandoc-1.17.1-2-amd64.deb

# 
script:
  - pandoc --version
  - python --version

# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
#  - git config user.name "kevinluolog"
#  - git config user.email "kevinluolog_72@163.com"
  # 替换同目录下的_config.yml文件中gh_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
#  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
#  - hexo deploy
# End: Build LifeCycle